edscrapers/scrapers/edoela/__init__.py, edscrapers/scrapers/edoela/crawler.py, edscrapers/scrapers/edoela/model.py, edscrapers/scrapers/edoela/parser.py, edscrapers/scrapers/edoela/scraper.py
=> Scraper for edoela

edscrapers/scrapers/edope/__init__.py, edscrapers/scrapers/edope/crawler.py, edscrapers/scrapers/edope/model.py, edscrapers/scrapers/edope/parser.py, edscrapers/scrapers/edope/scraper.py
=> Scraper for edope

edscrapers/scrapers/edoctae/__init__.py, edscrapers/scrapers/edoctae/crawler.py, edscrapers/scrapers/edoctae/model.py, edscrapers/scrapers/edoctae/parser.py, edscrapers/scrapers/edoctae/scraper.py
=> Scrapers - octae

edscrapers/scrapers/edope/crawler.py
=> Fixing edope crawler (P3 crawler). 

edscrapers/scrapers/edopepd/__init__.py, edscrapers/scrapers/edopepd/crawler.py, edscrapers/scrapers/edopepd/parser.py
=> Adding opepd crawler (P6 Crawling). 

edscrapers/scrapers/edoela/crawler.py
=> Fixing edoela Crawler (P4 Crawling). 

edscrapers/scrapers/edoctae/crawler.py
=> Fixing crawler edoctae (P2 Crawling). 

edscrapers/scrapers/oese/__init__.py, edscrapers/scrapers/oese/crawler.py, edscrapers/scrapers/oese/parser.py
=> Add OESE crawler

edscrapers/scrapers/edoctae/crawler.py
=> Fixing P2 Crawler. 

edscrapers/scrapers/edope/crawler.py, edscrapers/scrapers/edope/parser.py, edscrapers/scrapers/edope/parsers/__init__.py, edscrapers/scrapers/edope/parsers/ope_parser1.py, edscrapers/scrapers/edope/parsers/ope_parser2.py
- identified 2 variant page structures and parsers for P3 (edope_parser1 and edope_parser2)
- Tested parsers to ensure they produce Datasets with Resources and cause no errors
- Added extra regex to `allowed_regex` to ensure all links in `start_urls` can be crawled and parsed
=> edope-parser - completed parsers for edope (P3)

edscrapers/scrapers/edoela/crawler.py, edscrapers/scrapers/edoela/parser.py, edscrapers/scrapers/edoela/parsers/__init__.py, edscrapers/scrapers/edoela/parsers/oela_parser1.py
- Completed P4 parser
- Parser working with scrapy pipelines to produce Datasets with respurces
=> edoela-parser: completed edoela-parser P4 parser

Makefile, edscrapers/transformer/__init__.py, edscrapers/transformer/cli.py, edscrapers/transformer/helpers.py, edscrapers/transformer/models.py, edscrapers/transformer/transform.py, edscrapers/transformer/traverse.py
=> WIP - Adding transformer

edscrapers/scrapers/edopepd/crawler.py, edscrapers/scrapers/edopepd/parser.py, edscrapers/scrapers/edopepd/parsers/__init__.py, edscrapers/scrapers/edopepd/parsers/edopepd_parser1.py, edscrapers/scrapers/edopepd/parsers/edopepd_parser2.py
- Wrote 2 variant parsers for OPEPD pages
=> edopepd-parser: completed parser P6

edscrapers/scrapers/edosers/__init__.py, edscrapers/scrapers/edosers/parser.py, edscrapers/scrapers/edosers/parsers/__init__.py, edscrapers/scrapers/edosers/parsers/osers_parser1.py, edscrapers/scrapers/edosers/parsers/osers_parser2.py
=> Adding parser for OSERS (P5 Parsing). 

edscrapers/scrapers/base/parser.py, edscrapers/scrapers/edgov/crawler.py, edscrapers/scrapers/edgov/parser.py, edscrapers/scrapers/edgov/parsers/__init__.py, edscrapers/scrapers/edgov/parsers/edgov_parser1.py
- Completed parser for edgov
- Adjusted parser  in 'base' package to accept and filter resources by an additional 'deny_list' containing resources we DO NOT WANT
Closes #42
=> edgov-parser: edgov parser completed

edscrapers/transformers/base/__init__.py, edscrapers/transformers/base/cli.py, edscrapers/transformers/base/helpers.py, edscrapers/transformers/datajson/models.py, edscrapers/transformers/datajson/transform.py
- Adding 'n/a' description as default
- Adding publisher for missing offices
- Adding a transformer function for keywords
- Getting modified date from scraped files
ref #25
=> Fixing transformers. 

Pipfile, Pipfile.lock, edscrapers/transformers/base/helpers.py, tools/compare.py, tools/dashboard/app.py, tools/dashboard/json_parser.py, tools/dashboard/venn_diagram.py, tools/summary.py
A WIP pull request for the statistics dashboard.
=> Add dash powered dashboard

edscrapers/transformers/base/helpers.py, edscrapers/transformers/datajson/transform.py
- Include 'oese' Office name
- Changed dictionary access method
ref #25
=> Fix Transformers

edscrapers/scrapers/base/config.py, edscrapers/scrapers/oese/crawler.py, edscrapers/scrapers/oese/parser.py, edscrapers/scrapers/oese/parsers/__init__.py, edscrapers/scrapers/oese/parsers/oese_parser1.py
- Created one parser for OESE
- Adjusted scrapy config to turn off http caching (this enabled the retrieval of OESE pages)
- Adjusted crawler by adding `allowed_domains`
=> oese-parser: oese-parser P7 complete

edscrapers/transformers/datajson/models.py, edscrapers/transformers/datajson/transform.py
Changing landingPage to source_url in the dataset metadata list.
Tested with OCR, OCTAE data.json outputs.
ref #50
=> Adding source_url

.gitignore, edscrapers/scrapers/nces/NCES.md, edscrapers/scrapers/nces/crawler.py, edscrapers/scrapers/nces/parser.py, edscrapers/scrapers/nces/parsers/__init__.py, edscrapers/scrapers/nces/parsers/nces_parser4.py
- Created one more parser for page structure i.e nces_parser4
@nightsh when running the crawler on server, kindly note if there are any more pages which parser is not generating adequate datasets for. Didn't discover any more at my end
=> nces-parser-04: final parser for nces variant page structure

edscrapers/scrapers/base/helpers.py, edscrapers/scrapers/base/models.py, edscrapers/scrapers/edgov/parsers/edgov_parser1.py, edscrapers/scrapers/nces/parsers/nces_parser1.py, edscrapers/scrapers/nces/parsers/nces_parser2.py, edscrapers/scrapers/nces/parsers/nces_parser3.py, edscrapers/scrapers/nces/parsers/nces_parser4.py, edscrapers/scrapers/ocr/parsers/ocr_state_national_estimates_parser1.py, edscrapers/scrapers/ocr/parsers/ocr_state_national_estimates_parser2.py, edscrapers/scrapers/octae/parsers/octae_parser1.py, edscrapers/scrapers/octae/parsers/octae_parser2.py, edscrapers/scrapers/oela/parsers/oela_parser1.py, edscrapers/scrapers/oese/parsers/oese_parser1.py, edscrapers/scrapers/ope/parsers/ope_parser1.py, edscrapers/scrapers/ope/parsers/ope_parser2.py, edscrapers/scrapers/opepd/parsers/opepd_parser1.py, edscrapers/scrapers/opepd/parsers/opepd_parser2.py, edscrapers/scrapers/osers/parsers/osers_parser1.py, edscrapers/scrapers/osers/parsers/osers_parser2.py
=> Collect headers for resources

edscrapers/scrapers/octae/parsers/octae_parser1.py, edscrapers/scrapers/octae/parsers/octae_parser2.py, edscrapers/scrapers/ope/parsers/ope_parser1.py, edscrapers/scrapers/ope/parsers/ope_parser2.py
- Improved quality of P3 parser metadata by ensuring all datasets have a description
=> Ope parser 2

edscrapers/scrapers/octae/parsers/octae_parser1.py, edscrapers/scrapers/octae/parsers/octae_parser2.py
TASK TACKLED:
- improved metadata quality of parser by ensuring all parsers provide a description
=> [octae-parser-2][s]: improved parser metadata

edscrapers/scrapers/oela/parsers/oela_parser1.py
TASK TACKLED
- ensured P4 parser has a dataset description and publisher set
=> [oela-parser-2][s]: improve metadata gathering quality of P4 parser

edscrapers/scrapers/base/helpers.py, edscrapers/scrapers/edgov/crawler.py, edscrapers/scrapers/edgov/parsers/edgov_parser1.py
**TASKS TACKLED**
- fixed error in crawler by setting `allowed_domains`
- improved content outpur from parser by removing trailing white space characters from resource name and descriptions
- ensure all datasets have a title and description
- ensure resources have a name and description
=> Edgov parser phase3

edscrapers/scrapers/osers/crawler.py, edscrapers/scrapers/osers/parsers/osers_parser1.py, edscrapers/scrapers/osers/parsers/osers_parser2.py
- Ensured dataset have descriptions
- improved/refined crawler 'crawling' rule
- refined/improved the content for resource(s) description
=> osers-parser-phase3: improved parser content & metadata quality

edscrapers/scrapers/nces/parsers/nces_parser1.py, edscrapers/scrapers/nces/parsers/nces_parser2.py
- Based on code review discussions yesterday, i revisited the regex created to remove 'Table....' from dataset title. Adding @nightsh  cited example to the test, i improved the earlier regex for the 2 nces parsers
=> [nces-parser-improvements][improvement]: improved regex on dataset title

.gitignore, edscrapers/transformers/deduplicate/transform.py
- created a private helper function that allows querystring parameters to be flexibly stripped from url at the discretion of the developer
=> Deduplicate transform improvements

.gitignore, edscrapers/scrapers/nces/parsers/nces_parser1.py, edscrapers/scrapers/nces/parsers/nces_parser2.py, edscrapers/transformers/base/helpers.py, edscrapers/transformers/datajson/transform.py, edscrapers/transformers/sanitize/transform.py
TASK TACKLED:
- handled all sanitising tasks listed [here](https://hackmd.io/pnY--DyTRbmkJ-2pHXoeIw?both) AND [more here](https://hackmd.io/ZVTIEZ9MROy3fB4mUYv9bw)
=> Sanitize transform: apply data sanitizing steps

.gitignore, edscrapers/tools/stats/stats.py, edscrapers/transformers/rag/__init__.py, edscrapers/transformers/rag/transform.py
- RAG computation can now be performed on processed data (the default) and raw dataset
- RAG improvements produces no breaking change to dashboard code
- fixed bug on dashboard which prevented the loading of AIR.csv data
=> Rag transform 2: improved RAG computation 

edscrapers/scrapers/oese/parser.py, edscrapers/scrapers/oese/parsers/oese_parser1.py
TASK TACKLED:
- ensured all datasets have a description
- parser deals with non-text response
- ensure parser generates no errors when parsing
=> [oese-parser-improvements][m]: improved parser metadata & content quality

edscrapers/scrapers/opepd/parser.py, edscrapers/scrapers/opepd/parsers/opepd_parser1.py, edscrapers/scrapers/opepd/parsers/opepd_parser2.py
TASK TACKLED:
- Improved metdata for parser.
- improved content for parser
- ensured parser does not generate errors while parsing
=> [opepd-parser-improvements][m]: improved metadata & content quality

edscrapers/scrapers/fsa/parser.py, edscrapers/scrapers/fsa/parsers/fsa_parser1.py, edscrapers/scrapers/fsa/parsers/fsa_parser2.py
TASK TACKLED
- Handled bugs and improvement for FSA parser based on [QA feedback](https://hackmd.io/bFUtzC82RDK-mO4pkwWgag?both)
=> [parser-fixes][m]: fixed & improved FSA parser based on QA feedback

edscrapers/scrapers/oese/parsers/oese_parser1.py, edscrapers/tools/stats/stats.py
TASKS TACKLED
- Make OESE parser smart enough to prevent using the same element as multiple resource names
- fixed slight issue with dashboard where AIR data is downloaded on every viewing of insights page (even when the data has already been downloaded
this concludes all [QA feedback](https://hackmd.io/bFUtzC82RDK-mO4pkwWgag?both). 
Further issues on Dashboard may be tackled separately since it may not affect deployment/launch
=> Parser fixes 2

edscrapers/transformers/datajson/models.py, edscrapers/transformers/datajson/transform.py
TASK TACKLED:
Tackled all tasks listed in #118 and related to #57 .
Closes #57 ; but will leave #118 open till harvester is run on the output
=> Datajson sanitisation

.gitignore, edscrapers/cli.py, edscrapers/scrapers/base/pipelines.py, edscrapers/tools/dashboard/json_parser.py, edscrapers/tools/dashboard/pages/air.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/stats/air/compare.py, edscrapers/tools/stats/air/summary.py, edscrapers/tools/stats/stats.py, edscrapers/transformers/base/helpers.py, edscrapers/transformers/datajson/transform.py
- addressed a host of portability issues across the code base:
- removing static/hard-coded file urls
- ensuring that necessary directories/files are dynamically created
- etc
- ensure the dashboard is portable and can be easily started . Please use [these documented steps](https://hackmd.io/8BbRGqKXS-WFEaqBRKuOLg) for that
- fixed dashboard related [QA feedback](https://hackmd.io/bFUtzC82RDK-mO4pkwWgag?both)
=> Dashboard fixes & code portability

edscrapers/scrapers/fsa/parser.py
Added the code implementation for collections and sources to FSA
=> [collection-sources-fsa][m]: implement collection and sources for FSA

edscrapers/scrapers/octae/parsers/octae_parser1.py, edscrapers/scrapers/octae/parsers/octae_parser2.py
TASKS:
- implement sources and collections for OCTAE
=> Octae collections sources

edscrapers/scrapers/oela/parser.py, edscrapers/scrapers/oela/parsers/oela_parser1.py
TASKS TACKLED
- implemented collections and sources for oela
- fixed issue when scrapy provides non-text content to parser
=> OELA collections sources

edscrapers/scrapers/edgov/parsers/edgov_parser1.py, edscrapers/scrapers/nces/parsers/nces_parser1.py, edscrapers/scrapers/oese/parsers/oese_parser1.py, edscrapers/scrapers/opepd/parsers/opepd_parser1.py, edscrapers/scrapers/opepd/parsers/opepd_parser2.py, edscrapers/scrapers/osers/parsers/osers_parser1.py, edscrapers/scrapers/osers/parsers/osers_parser2.py
Sources and collections effected for all offices
=> [collections-sources-imp-linvestigate][l]: implementation of sources and collections

edscrapers/tools/dashboard/app.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/pages/rag.py, edscrapers/tools/dashboard/pages/trends.py, edscrapers/tools/dashboard/tooltips.py, edscrapers/tools/dashboard/utils.py
ref #133
- General improvements
- Title size
- Create a footer for logos placement
- Remove the small icons from the top of the graphs
- Styling changes
- Insights Page
- Add a total in the tables
- Fix table order: from highest to lowest number
- Reorder the graphs
- Add Titles
- Add Tooltips
- Quality Page
- Remove the score column and renamed the percentage column as “Score”
- Trends Page
- Join separated graphs in only one multiline graph
- Styling
- Add Tooltip
=> [WIP] - Dashboard Improvements

.gitignore, edscrapers/tools/dashboard/app.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/pages/rag.py, edscrapers/tools/dashboard/pages/trends.py, edscrapers/tools/dashboard/tooltips.py, edscrapers/tools/dashboard/utils.py
ref #133
* General improvements
* Title size
* Create a footer for logos placement
* Remove the small icons from the top of the graphs
* Styling changes
* Insights Page
* Add a total in the tables
* Fix table order: from highest to lowest number
* Reorder the graphs
* Add Titles
* Add Tooltips
* Change sidebar label
* Relabel office as Publisher
* Add resources by Publisher section (graph + table)
* Order of graphs
* Quality Page
* Remove the score column and renamed the percentage column as “Score”
* Trends Page
* Join separated graphs in only one multiline graph
* Styling
* Add Tooltip
=> [WIP] Dashboard insights page

edscrapers/tools/dashboard/app.py, edscrapers/tools/dashboard/pages/components.py, edscrapers/tools/dashboard/pages/dashboard.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/pages/rag.py, edscrapers/tools/dashboard/tooltips.py
Dashboard improvements ref #133
- Add notes to trends page
- Fix tooltips
=> Dashboard notes

edscrapers/tools/dashboard/app.py, edscrapers/tools/dashboard/pages/components.py, edscrapers/tools/dashboard/pages/dashboard.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/tooltips.py
Dashboard Improvements ref #133
- add dashboard home page
- total datasets in the portal
- pie chart
=> Dashboard home page

edscrapers/tools/dashboard/pages/components.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/tooltips.py
Dashboard Improvements ref #133
- Change insights page
- 2 rows of data the first is “Based on original scraper” and the second is “Ingested into data portal”
- Refactoring
- Fix tooltips
=> Dashboard insights page

edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/pages/rag.py, edscrapers/tools/dashboard/pages/tooltips.py, edscrapers/tools/dashboard/pages/trends.py
Dashboard improvements - ref #33
- fix tooltips
=> Fix Tooltips

edscrapers/tools/dashboard/app.py, edscrapers/tools/dashboard/pages/air.py
Dashboard Improvements - ref #133
- Remove air page from sidebar
- Leave air.py file that contains methods to get some data
=> Remove air page

edscrapers/tools/dashboard/app.py, edscrapers/tools/dashboard/ckan_api.py, edscrapers/tools/dashboard/pages/dashboard.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/pages/tooltips.py, edscrapers/tools/dashboard/pages/trends.py
- Get data from ckan api endpoint
- Fix dashboard home page
- Insert a trend graph line for fsa
=> Dashboard portal data

edscrapers/tools/dashboard/pages/insights.py
**Insights Page is not working on Master Branch** so that I got an old commit and create this branch for these fixes. From here: https://github.com/CivicActions/edscrapers/tree/ad37f1fb38ccc60e2639b58552a86e75bc6adde6
Probably this can be merged properly as I only changed the pages on the dashboard.
- Fix graph legends
=> Dashboard improvements - ref #133

edscrapers/transformers/datajson/transform.py
Reverts CivicActions/edscrapers#182
=> Revert "Make datajson transformer work with both single values and lists of Sources / Collections"

edscrapers/transformers/datajson/transform.py
ref #185
- The default value should be 018:00
=> Change the default value of Bureau Code field. 

edscrapers/transformers/datajson/models.py
refs #188 https://github.com/CivicActions/ckanext-ed/issues/330
- Update the transformer datajson output adding "amended_by_user" field
=> Add metadata field to identify scraped datasets

edscrapers/scrapers/base/graph.py, edscrapers/transformers/collections/transform.py, edscrapers/transformers/deduplicate/transform.py
implemented deduplication for the graph model
=> [graph-deduplication][l]: implemented deduplication for the graph model

edscrapers/transformers/sanitize/transform.py
ref #192
- mark datasets with only txt files as resources for removal.
=> Remove datasets with only txt files as resources. 

edscrapers/transformers/base/helpers.py, edscrapers/transformers/datajson/transform.py
ref #199
- check the length of the publisher name
- guess the office email based on the long publisher name
See analysis on #199
=> Fix invalid office email. 

edscrapers/scrapers/base/config.py, edscrapers/scrapers/rems/__init__.py, edscrapers/scrapers/rems/crawler.py, edscrapers/scrapers/rems/parser.py, edscrapers/scrapers/rems/parsers/__init__.py, edscrapers/scrapers/rems/parsers/rems_parser1.py
Needs:
* title
* some crawling rules to avoid circling the same page with different
query string
=> REMS scraper

edscrapers/scrapers/dashboard/crawler.py
- remove useless parameters from urls
=> Improve dashboard.ed crawler

edscrapers/transformers/base/helpers.py, edscrapers/transformers/datajson/transform.py
- unparse html chars in dataset/resources names
- remove "None" strings in the datasets descriptions
- fix rems and dashboard offices Publisher
- fix rems and dashboard offices email
=> Improve datajson transformer for rems and dashboard scrapers

edscrapers/scrapers/edgov/offices_map.py, edscrapers/tools/dashboard/ckan_api.py, edscrapers/tools/dashboard/pages/helpers.py, edscrapers/tools/dashboard/pages/insights.py, edscrapers/tools/dashboard/pages/rag.py, edscrapers/tools/dashboard/pages/trends.py
Closes #207
- show Publisher titles instead of names
- merge data from same Publishers with different names
- fix trends graph legend
=> Updating the dashboard to track edited data profile metrics. 

.gitignore, edscrapers/scrapers/edgov/offices_map.py, edscrapers/tools/stats/stats.py, edscrapers/transformers/sanitize/transform.py
- now the stats dataframe will ignore datasets removed by sanitizer
- updated edgov offices map
- cleaned up the sanitizer and removed dashboard and rems URLs from edgov
=> Stats for resource sizes, sanitizer tweaks

edscrapers/tools/dashboard/pages/insights.py
Closes #210
- test if there is the Publisher Title, if not display the Name
=> Fix insights page. 

edscrapers/scrapers/edgov/offices_map.py, edscrapers/tools/dashboard/pages/insights.py
- white house initiatives offices
=> Display offices titles instead of offices names.

edscrapers/tools/dashboard/app.py
- move the CSS file to a GitCDN link.
=> Fix missing CSS file url
